### PR TITLE
[mainnet] Rerun gas config update post MCP

### PR DESCRIPTION
**Pull request by anikaraghu**
The MCP upgrade had already received signatures using the old gas config value, so we executed it which reset the gas config to what is was before the upgrade yesterday. Reruning to get back to where we were.

### CODE REVIEW

**Review by 0x00101010 — APPROVED** [review]

**Review by cody-wang-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for cody-wang-cb @ 2024-06-28 17:22:12 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by cody-wang-cb — APPROVED** [review]

**Review by 0x00101010 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for cody-wang-cb @ 2024-06-28 17:29:46 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by cb-heimdall** [comment]
Review Error for 0x00101010 @ 2024-06-28 17:31:40 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by cody-wang-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for cody-wang-cb @ 2024-06-28 20:32:14 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by andrew-booth-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for andrew-booth-cb @ 2024-06-28 20:35:24 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by andrew-booth-cb — APPROVED** [review]

**Review by 0x00101010 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for andrew-booth-cb @ 2024-06-28 20:49:41 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by cb-heimdall** [comment]
Review Error for 0x00101010 @ 2024-06-28 20:49:52 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by andrew-booth-cb — APPROVED** [review]

**Review by 0x00101010 — APPROVED** [review]

**Pull request merged**
