### PR TITLE
[mainnet] EAS support OP runbook review

### PR DESCRIPTION
**Pull request by anikaraghu**
Need to get OP's review on the EAS support runbook.

Changes:
* `make deps` step was missing
* make more clear that OP signers need to run `make sign-op` instead of `make sign-cb`

### CODE REVIEW

**Comment by maurelian** [comment]
Reviewed. This LGTM.

**Review by maurelian — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for maurelian @ 2023-09-05 15:00:55 UTC
User must have write permissions to review

**Review by maurelian — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for maurelian @ 2023-09-05 20:19:18 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by maurelian — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for maurelian @ 2023-09-05 20:20:40 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by danyalprout — APPROVED** [review]

**Review by dapperscene6 — APPROVED** [review]

**Pull request merged**
